"""add_lead_score_numeric_and_notified_hot_at

Revision ID: 7fa54922a7af
Revises: 0009
Create Date: 2026-07-13 02:04:52.398957
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fa54922a7af'
down_revision: Union[str, None] = '0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('clients', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('idx_clients_agency_id'), table_name='clients')
    op.drop_index(op.f('uidx_clients_wa_phone'), table_name='clients', postgresql_where='(wa_phone_number_id IS NOT NULL)')
    op.alter_column('daily_stats', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_documents_client_id'), table_name='documents')
    op.add_column('leads', sa.Column('lead_score_numeric', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('notified_hot_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('leads', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'WhatsApp User'::character varying"))
    op.alter_column('leads', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'New Lead'::character varying"))
    op.alter_column('leads', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('leads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_leads_client_id'), table_name='leads')
    op.drop_index(op.f('idx_leads_phone'), table_name='leads')
    op.drop_index(op.f('idx_leads_status'), table_name='leads')
    op.drop_constraint(op.f('leads_phone_key'), 'leads', type_='unique')
    op.create_index(op.f('ix_leads_phone'), 'leads', ['phone'], unique=True)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.alter_column('messages', 'msg_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'text'::character varying"))
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_messages_created'), table_name='messages')
    op.drop_constraint(op.f('unique_wa_message_id'), 'messages', type_='unique')
    op.alter_column('pipeline_stages', 'position',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('pipeline_stages', 'is_won',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('pipeline_stages', 'is_lost',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_pipeline_client'), table_name='pipeline_stages')
    op.drop_constraint(op.f('pipeline_stages_client_id_name_key'), 'pipeline_stages', type_='unique')
    op.alter_column('prompt_templates', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('prompt_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('usage_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_usage_events_client_id'), table_name='usage_events')
    op.drop_index(op.f('idx_usage_events_created_at'), table_name='usage_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_usage_events_created_at'), 'usage_events', ['created_at'], unique=False)
    op.create_index(op.f('idx_usage_events_client_id'), 'usage_events', ['client_id'], unique=False)
    op.alter_column('usage_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('prompt_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('prompt_templates', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_unique_constraint(op.f('pipeline_stages_client_id_name_key'), 'pipeline_stages', ['client_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_pipeline_client'), 'pipeline_stages', ['client_id', 'position'], unique=False)
    op.alter_column('pipeline_stages', 'is_lost',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('pipeline_stages', 'is_won',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('pipeline_stages', 'position',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.create_unique_constraint(op.f('unique_wa_message_id'), 'messages', ['wa_message_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_messages_created'), 'messages', ['created_at'], unique=False)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('messages', 'msg_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'text'::character varying"))
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_phone'), table_name='leads')
    op.create_unique_constraint(op.f('leads_phone_key'), 'leads', ['phone'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_leads_status'), 'leads', ['status'], unique=False)
    op.create_index(op.f('idx_leads_phone'), 'leads', ['phone'], unique=False)
    op.create_index(op.f('idx_leads_client_id'), 'leads', ['client_id'], unique=False)
    op.alter_column('leads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('leads', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('leads', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'New Lead'::character varying"))
    op.alter_column('leads', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'WhatsApp User'::character varying"))
    op.drop_column('leads', 'notified_hot_at')
    op.drop_column('leads', 'lead_score_numeric')
    op.create_index(op.f('idx_documents_client_id'), 'documents', ['client_id'], unique=False)
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('daily_stats', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('uidx_clients_wa_phone'), 'clients', ['wa_phone_number_id'], unique=True, postgresql_where='(wa_phone_number_id IS NOT NULL)')
    op.create_index(op.f('idx_clients_agency_id'), 'clients', ['agency_id'], unique=False)
    op.alter_column('clients', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('clients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
